#!/bin/bash -e
# Copyright (C) 2022 Simo Sorce <simo@redhat.com>
# SPDX-License-Identifier: Apache-2.0

source ${TESTSSRCDIR}/helpers.sh

title PARA "Check we can fetch certifiatce objects"

ossl '
x509 -in ${CRTURI} -subject -out ${TMPPDIR}/crt-subj.txt'
DATA=$(cat ${TMPPDIR}/crt-subj.txt)
CHECK="subject=O = PKCS11 Provider, CN = My Test Cert"
if [[ ! ${DATA} =~ ${CHECK} ]]; then
    echo "Cert not found looking for ${CHECK}"
    exit 1
fi

ossl '
x509 -in ${ECCRTURI} -subject -out ${TMPPDIR}/eccrt-subj.txt'
DATA=$(cat ${TMPPDIR}/eccrt-subj.txt)
CHECK="subject=O = PKCS11 Provider, CN = My EC Cert"
if [[ ! ${DATA} =~ ${CHECK} ]]; then
    echo "Cert not found looking for ${CHECK}"
    exit 1
fi

exit 0
