#!/bin/bash -e
# Copyright (C) 2025 Jakub Zelenka <jakub.openssl@gmail.com>
# SPDX-License-Identifier: Apache-2.0

source "${TESTSSRCDIR}/helpers.sh"

ORIG_OPENSSL_CONF=${OPENSSL_CONF}
sed -e "s/#pkcs11-module-default-slot-id/pkcs11-module-default-slot-id = 52/" \
    -e "s/^pkcs11-module-token-pin.*$/pkcs11-module-token-pin = 11111111/" \
    "${OPENSSL_CONF}" > "${OPENSSL_CONF}.defaultslot"
export OPENSSL_CONF=${OPENSSL_CONF}.defaultslot

title PARA "Test PKCS11 SLOTS default slot - pub key storing"
"${TESTBLDDIR}/tstorepubkey" "${PUBURI2}"

title PARA "Test PKCS11 SLOTS default slot - checking slot"
pkcs11-tool --module "${P11LIB}" --slot 52 -O | grep 'id=%02%01;object=testKey' -q

export OPENSSL_CONF=${ORIG_OPENSSL_CONF}
