#!/bin/bash -e
# Copyright (C) 2022 Simo sorce <simo@redhat.com>
# SPDX-License-Identifier: Apache-2.0

TEST_PARAMS=(${1//-/ })

TEST_NAME=$(basename ${TEST_PARAMS[0]})
TOKEN_DRIVER=${TEST_PARAMS[1]}

COMMAND="./t${TEST_NAME}"

for option in "${TEST_PARAMS[@]}"; do
    if [[ "$option" == "proxy" ]]; then
        COMMAND="./softhsm-proxy.sh $COMMAND"
    fi
done

source ./tmp.${TOKEN_DRIVER}/testvars

echo "Executing ${COMMAND}"
${COMMAND}
