#!/bin/bash -e
# Copyright 2025 NXP
# SPDX-License-Identifier: Apache-2.0

source "${TESTSSRCDIR}/helpers.sh"

title PARA "Test HMAC support"

# Use a large key size, softhsm requires it to be >= digest size
HMAC_HEX_KEY=aaaabbbbaaaabbbbaaaabbbbaaaabbbbaaaabbbbaaaabbbbaaaabbbbaaaabbbb

declare -A digests=(
    # These HMAC digests should be generally supported
    ["supported"]="sha1 SSL3-SHA1 SHA1 SHA256 SHA-256 SHA2-256 SHA384 SHA-384 SHA2-384 SHA512 SHA-512 SHA2-512"

    ["optional"]="SHA512-224 SHA-512/224 SHA2-512/224 SHA512-256 SHA-512/256 SHA2-512/256"
)

for key in "${!digests[@]}"; do
    IFS=" " read -r -a values <<< "${digests[$key]}"
    FAIL=0

    for digest in "${values[@]}"; do
        ossl "
        mac -digest ${digest}
            -macopt key:${HMAC_HEX_KEY}
            -in ${RAND64FILE}
            -out ${TMPPDIR}/hmac-out-pkcs11.bin
            -propquery provider=pkcs11
            hmac" || FAIL=1
        if [ $FAIL -eq 1 ]; then
            if [ "${key}" = "supported" ]; then
                exit 1
            else
                continue
            fi
        fi

        ossl "
        mac -digest ${digest}
            -macopt key:${HMAC_HEX_KEY}
            -in ${RAND64FILE}
            -out ${TMPPDIR}/hmac-out.bin
            hmac" || FAIL=1
        if [ $FAIL -eq 1 ]; then
            exit 1
        fi

        diff "${TMPPDIR}/hmac-out-pkcs11.bin" "${TMPPDIR}/hmac-out.bin"
    done
done
