/* Copyright (C) 2026 Simo Sorce <simo@redhat.com>
   SPDX-License-Identifier: Apache-2.0 */

#include "provider.h"

#define CASE_TBID_TO_CKM(name) \
    case TBID_##name: \
        return CKM_##name

#define CASE_CKM_TO_TBID(name) \
    case CKM_##name: \
        return TBID_##name

CK_MECHANISM_TYPE p11prov_tbid_to_mech(enum p11prov_mech_tbid tbid)
{
    switch (tbid) {
        CASE_TBID_TO_CKM(RSA_PKCS_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(RSA_PKCS);
        CASE_TBID_TO_CKM(SHA1_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA224_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA256_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA384_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA512_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA3_224_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA3_256_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA3_384_RSA_PKCS);
        CASE_TBID_TO_CKM(SHA3_512_RSA_PKCS);
        CASE_TBID_TO_CKM(RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA1_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA256_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA384_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA512_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA224_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA3_256_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA3_384_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA3_512_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(SHA3_224_RSA_PKCS_PSS);
        CASE_TBID_TO_CKM(RSA_PKCS_OAEP);
        CASE_TBID_TO_CKM(RSA_X_509);
        CASE_TBID_TO_CKM(RSA_X9_31);
        CASE_TBID_TO_CKM(RSA_X9_31_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(EC_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(ECDSA);
        CASE_TBID_TO_CKM(ECDSA_SHA1);
        CASE_TBID_TO_CKM(ECDSA_SHA224);
        CASE_TBID_TO_CKM(ECDSA_SHA256);
        CASE_TBID_TO_CKM(ECDSA_SHA384);
        CASE_TBID_TO_CKM(ECDSA_SHA512);
        CASE_TBID_TO_CKM(ECDSA_SHA3_224);
        CASE_TBID_TO_CKM(ECDSA_SHA3_256);
        CASE_TBID_TO_CKM(ECDSA_SHA3_384);
        CASE_TBID_TO_CKM(ECDSA_SHA3_512);
        CASE_TBID_TO_CKM(ECDH1_DERIVE);
        CASE_TBID_TO_CKM(ECDH1_COFACTOR_DERIVE);
        CASE_TBID_TO_CKM(EC_EDWARDS_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(EC_MONTGOMERY_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(EDDSA);
        CASE_TBID_TO_CKM(HKDF_DERIVE);
        CASE_TBID_TO_CKM(SHA_1);
        CASE_TBID_TO_CKM(SHA_1_HMAC);
        CASE_TBID_TO_CKM(SHA_1_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA1_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA_1_KEY_GEN);
        CASE_TBID_TO_CKM(SHA224);
        CASE_TBID_TO_CKM(SHA224_HMAC);
        CASE_TBID_TO_CKM(SHA224_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA224_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA224_KEY_GEN);
        CASE_TBID_TO_CKM(SHA256);
        CASE_TBID_TO_CKM(SHA256_HMAC);
        CASE_TBID_TO_CKM(SHA256_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA256_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA256_KEY_GEN);
        CASE_TBID_TO_CKM(SHA384);
        CASE_TBID_TO_CKM(SHA384_HMAC);
        CASE_TBID_TO_CKM(SHA384_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA384_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA384_KEY_GEN);
        CASE_TBID_TO_CKM(SHA512);
        CASE_TBID_TO_CKM(SHA512_HMAC);
        CASE_TBID_TO_CKM(SHA512_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA512_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA512_KEY_GEN);
        CASE_TBID_TO_CKM(SHA512_224);
        CASE_TBID_TO_CKM(SHA512_224_HMAC);
        CASE_TBID_TO_CKM(SHA512_224_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA512_224_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA512_224_KEY_GEN);
        CASE_TBID_TO_CKM(SHA512_256);
        CASE_TBID_TO_CKM(SHA512_256_HMAC);
        CASE_TBID_TO_CKM(SHA512_256_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA512_256_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA512_256_KEY_GEN);
        CASE_TBID_TO_CKM(SHA512_T);
        CASE_TBID_TO_CKM(SHA512_T_HMAC);
        CASE_TBID_TO_CKM(SHA512_T_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA512_T_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA512_T_KEY_GEN);
        CASE_TBID_TO_CKM(SHA3_224);
        CASE_TBID_TO_CKM(SHA3_224_HMAC);
        CASE_TBID_TO_CKM(SHA3_224_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA3_224_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA3_224_KEY_GEN);
        CASE_TBID_TO_CKM(SHA3_256);
        CASE_TBID_TO_CKM(SHA3_256_HMAC);
        CASE_TBID_TO_CKM(SHA3_256_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA3_256_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA3_256_KEY_GEN);
        CASE_TBID_TO_CKM(SHA3_384);
        CASE_TBID_TO_CKM(SHA3_384_HMAC);
        CASE_TBID_TO_CKM(SHA3_384_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA3_384_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA3_384_KEY_GEN);
        CASE_TBID_TO_CKM(SHA3_512);
        CASE_TBID_TO_CKM(SHA3_512_HMAC);
        CASE_TBID_TO_CKM(SHA3_512_HMAC_GENERAL);
        CASE_TBID_TO_CKM(SHA3_512_KEY_DERIVATION);
        CASE_TBID_TO_CKM(SHA3_512_KEY_GEN);
        CASE_TBID_TO_CKM(ML_DSA_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(ML_DSA);
        CASE_TBID_TO_CKM(HASH_ML_DSA);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA224);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA256);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA384);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA512);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA3_224);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA3_256);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA3_384);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHA3_512);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHAKE128);
        CASE_TBID_TO_CKM(HASH_ML_DSA_SHAKE256);
        CASE_TBID_TO_CKM(ML_KEM_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(ML_KEM);
        CASE_TBID_TO_CKM(SLH_DSA_KEY_PAIR_GEN);
        CASE_TBID_TO_CKM(SLH_DSA);
        CASE_TBID_TO_CKM(HASH_SLH_DSA);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA224);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA256);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA384);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA512);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA3_224);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA3_256);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA3_384);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHA3_512);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHAKE128);
        CASE_TBID_TO_CKM(HASH_SLH_DSA_SHAKE256);
        CASE_TBID_TO_CKM(AES_KEY_GEN);
        CASE_TBID_TO_CKM(AES_ECB);
        CASE_TBID_TO_CKM(AES_CBC);
        CASE_TBID_TO_CKM(AES_CBC_PAD);
        CASE_TBID_TO_CKM(AES_OFB);
        CASE_TBID_TO_CKM(AES_CFB128);
        CASE_TBID_TO_CKM(AES_CFB1);
        CASE_TBID_TO_CKM(AES_CFB8);
        CASE_TBID_TO_CKM(AES_CTR);
        CASE_TBID_TO_CKM(AES_CTS);
        CASE_TBID_TO_CKM(AES_GCM);
        CASE_TBID_TO_CKM(AES_MAC);
        CASE_TBID_TO_CKM(AES_MAC_GENERAL);
        CASE_TBID_TO_CKM(AES_CCM);
        CASE_TBID_TO_CKM(AES_CMAC);
        CASE_TBID_TO_CKM(AES_CMAC_GENERAL);
        CASE_TBID_TO_CKM(AES_XCBC_MAC);
        CASE_TBID_TO_CKM(AES_XCBC_MAC_96);
        CASE_TBID_TO_CKM(AES_GMAC);
        CASE_TBID_TO_CKM(CHACHA20_POLY1305);
        CASE_TBID_TO_CKM(GENERIC_SECRET_KEY_GEN);
    default:
        return CK_UNAVAILABLE_INFORMATION;
    }
}

int p11prov_mech_to_tbid(CK_MECHANISM_TYPE mech)
{
    switch (mech) {
        CASE_CKM_TO_TBID(RSA_PKCS_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(RSA_PKCS);
        CASE_CKM_TO_TBID(SHA1_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA224_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA256_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA384_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA512_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA3_224_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA3_256_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA3_384_RSA_PKCS);
        CASE_CKM_TO_TBID(SHA3_512_RSA_PKCS);
        CASE_CKM_TO_TBID(RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA1_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA256_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA384_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA512_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA224_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA3_256_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA3_384_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA3_512_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(SHA3_224_RSA_PKCS_PSS);
        CASE_CKM_TO_TBID(RSA_PKCS_OAEP);
        CASE_CKM_TO_TBID(RSA_X_509);
        CASE_CKM_TO_TBID(RSA_X9_31);
        CASE_CKM_TO_TBID(RSA_X9_31_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(EC_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(ECDSA);
        CASE_CKM_TO_TBID(ECDSA_SHA1);
        CASE_CKM_TO_TBID(ECDSA_SHA224);
        CASE_CKM_TO_TBID(ECDSA_SHA256);
        CASE_CKM_TO_TBID(ECDSA_SHA384);
        CASE_CKM_TO_TBID(ECDSA_SHA512);
        CASE_CKM_TO_TBID(ECDSA_SHA3_224);
        CASE_CKM_TO_TBID(ECDSA_SHA3_256);
        CASE_CKM_TO_TBID(ECDSA_SHA3_384);
        CASE_CKM_TO_TBID(ECDSA_SHA3_512);
        CASE_CKM_TO_TBID(ECDH1_DERIVE);
        CASE_CKM_TO_TBID(ECDH1_COFACTOR_DERIVE);
        CASE_CKM_TO_TBID(EC_EDWARDS_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(EC_MONTGOMERY_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(EDDSA);
        CASE_CKM_TO_TBID(HKDF_DERIVE);
        CASE_CKM_TO_TBID(SHA_1);
        CASE_CKM_TO_TBID(SHA_1_HMAC);
        CASE_CKM_TO_TBID(SHA_1_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA1_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA_1_KEY_GEN);
        CASE_CKM_TO_TBID(SHA224);
        CASE_CKM_TO_TBID(SHA224_HMAC);
        CASE_CKM_TO_TBID(SHA224_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA224_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA224_KEY_GEN);
        CASE_CKM_TO_TBID(SHA256);
        CASE_CKM_TO_TBID(SHA256_HMAC);
        CASE_CKM_TO_TBID(SHA256_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA256_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA256_KEY_GEN);
        CASE_CKM_TO_TBID(SHA384);
        CASE_CKM_TO_TBID(SHA384_HMAC);
        CASE_CKM_TO_TBID(SHA384_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA384_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA384_KEY_GEN);
        CASE_CKM_TO_TBID(SHA512);
        CASE_CKM_TO_TBID(SHA512_HMAC);
        CASE_CKM_TO_TBID(SHA512_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA512_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA512_KEY_GEN);
        CASE_CKM_TO_TBID(SHA512_224);
        CASE_CKM_TO_TBID(SHA512_224_HMAC);
        CASE_CKM_TO_TBID(SHA512_224_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA512_224_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA512_224_KEY_GEN);
        CASE_CKM_TO_TBID(SHA512_256);
        CASE_CKM_TO_TBID(SHA512_256_HMAC);
        CASE_CKM_TO_TBID(SHA512_256_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA512_256_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA512_256_KEY_GEN);
        CASE_CKM_TO_TBID(SHA512_T);
        CASE_CKM_TO_TBID(SHA512_T_HMAC);
        CASE_CKM_TO_TBID(SHA512_T_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA512_T_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA512_T_KEY_GEN);
        CASE_CKM_TO_TBID(SHA3_224);
        CASE_CKM_TO_TBID(SHA3_224_HMAC);
        CASE_CKM_TO_TBID(SHA3_224_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA3_224_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA3_224_KEY_GEN);
        CASE_CKM_TO_TBID(SHA3_256);
        CASE_CKM_TO_TBID(SHA3_256_HMAC);
        CASE_CKM_TO_TBID(SHA3_256_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA3_256_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA3_256_KEY_GEN);
        CASE_CKM_TO_TBID(SHA3_384);
        CASE_CKM_TO_TBID(SHA3_384_HMAC);
        CASE_CKM_TO_TBID(SHA3_384_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA3_384_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA3_384_KEY_GEN);
        CASE_CKM_TO_TBID(SHA3_512);
        CASE_CKM_TO_TBID(SHA3_512_HMAC);
        CASE_CKM_TO_TBID(SHA3_512_HMAC_GENERAL);
        CASE_CKM_TO_TBID(SHA3_512_KEY_DERIVATION);
        CASE_CKM_TO_TBID(SHA3_512_KEY_GEN);
        CASE_CKM_TO_TBID(ML_DSA_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(ML_DSA);
        CASE_CKM_TO_TBID(HASH_ML_DSA);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA224);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA256);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA384);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA512);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA3_224);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA3_256);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA3_384);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHA3_512);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHAKE128);
        CASE_CKM_TO_TBID(HASH_ML_DSA_SHAKE256);
        CASE_CKM_TO_TBID(ML_KEM_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(ML_KEM);
        CASE_CKM_TO_TBID(SLH_DSA_KEY_PAIR_GEN);
        CASE_CKM_TO_TBID(SLH_DSA);
        CASE_CKM_TO_TBID(HASH_SLH_DSA);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA224);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA256);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA384);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA512);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA3_224);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA3_256);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA3_384);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHA3_512);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHAKE128);
        CASE_CKM_TO_TBID(HASH_SLH_DSA_SHAKE256);
        CASE_CKM_TO_TBID(AES_KEY_GEN);
        CASE_CKM_TO_TBID(AES_ECB);
        CASE_CKM_TO_TBID(AES_CBC);
        CASE_CKM_TO_TBID(AES_CBC_PAD);
        CASE_CKM_TO_TBID(AES_OFB);
        CASE_CKM_TO_TBID(AES_CFB128);
        CASE_CKM_TO_TBID(AES_CFB1);
        CASE_CKM_TO_TBID(AES_CFB8);
        CASE_CKM_TO_TBID(AES_CTR);
        CASE_CKM_TO_TBID(AES_CTS);
        CASE_CKM_TO_TBID(AES_GCM);
        CASE_CKM_TO_TBID(AES_MAC);
        CASE_CKM_TO_TBID(AES_MAC_GENERAL);
        CASE_CKM_TO_TBID(AES_CCM);
        CASE_CKM_TO_TBID(AES_CMAC);
        CASE_CKM_TO_TBID(AES_CMAC_GENERAL);
        CASE_CKM_TO_TBID(AES_XCBC_MAC);
        CASE_CKM_TO_TBID(AES_XCBC_MAC_96);
        CASE_CKM_TO_TBID(AES_GMAC);
        CASE_CKM_TO_TBID(CHACHA20_POLY1305);
        CASE_CKM_TO_TBID(GENERIC_SECRET_KEY_GEN);
    default:
        return -1;
    }
}

CK_RV p11prov_get_mech_state_table(P11PROV_CTX *ctx, bool available[TBID_SIZE])
{
    P11PROV_SLOTS_CTX *slots;
    P11PROV_SLOT *slot;
    int slot_idx = 0;
    CK_RV ret;

    ret = p11prov_take_slots(ctx, &slots);
    if (ret != CKR_OK) {
        return ret;
    }

    for (slot = p11prov_fetch_slot(slots, &slot_idx); slot != NULL;
         slot = p11prov_fetch_slot(slots, &slot_idx)) {

        CK_MECHANISM_TYPE *mechs;
        int nmechs;
        nmechs = p11prov_slot_get_mechanisms(slot, &mechs);

        for (int i = 0; i < nmechs; i++) {
            int tbid = p11prov_mech_to_tbid(mechs[i]);
            if (tbid == -1) {
                continue;
            }
            available[tbid] = true;
        }
    }
    p11prov_return_slots(slots);

    return CKR_OK;
}

void p11prov_assign_alg(OSSL_ALGORITHM *dest, const OSSL_ALGORITHM *algs,
                        int idx, const char *fips_property)
{
    *dest = algs[idx];
    if (fips_property) {
        dest->property_definition = fips_property;
    }
}
