/* Copyright (C) 2026 Simo Sorce <simo@redhat.com>
   SPDX-License-Identifier: Apache-2.0 */

#include "provider.h"

CK_MECHANISM_TYPE p11prov_tbid_to_mech(enum p11prov_mech_tbid tbid)
{
    switch (tbid) {
    case TBID_RSA_PKCS_KEY_PAIR_GEN:
        return CKM_RSA_PKCS_KEY_PAIR_GEN;
    case TBID_RSA_PKCS:
        return CKM_RSA_PKCS;
    case TBID_SHA1_RSA_PKCS:
        return CKM_SHA1_RSA_PKCS;
    case TBID_SHA224_RSA_PKCS:
        return CKM_SHA224_RSA_PKCS;
    case TBID_SHA256_RSA_PKCS:
        return CKM_SHA256_RSA_PKCS;
    case TBID_SHA384_RSA_PKCS:
        return CKM_SHA384_RSA_PKCS;
    case TBID_SHA512_RSA_PKCS:
        return CKM_SHA512_RSA_PKCS;
    case TBID_SHA3_224_RSA_PKCS:
        return CKM_SHA3_224_RSA_PKCS;
    case TBID_SHA3_256_RSA_PKCS:
        return CKM_SHA3_256_RSA_PKCS;
    case TBID_SHA3_384_RSA_PKCS:
        return CKM_SHA3_384_RSA_PKCS;
    case TBID_SHA3_512_RSA_PKCS:
        return CKM_SHA3_512_RSA_PKCS;
    case TBID_RSA_PKCS_PSS:
        return CKM_RSA_PKCS_PSS;
    case TBID_SHA1_RSA_PKCS_PSS:
        return CKM_SHA1_RSA_PKCS_PSS;
    case TBID_SHA256_RSA_PKCS_PSS:
        return CKM_SHA256_RSA_PKCS_PSS;
    case TBID_SHA384_RSA_PKCS_PSS:
        return CKM_SHA384_RSA_PKCS_PSS;
    case TBID_SHA512_RSA_PKCS_PSS:
        return CKM_SHA512_RSA_PKCS_PSS;
    case TBID_SHA224_RSA_PKCS_PSS:
        return CKM_SHA224_RSA_PKCS_PSS;
    case TBID_SHA3_256_RSA_PKCS_PSS:
        return CKM_SHA3_256_RSA_PKCS_PSS;
    case TBID_SHA3_384_RSA_PKCS_PSS:
        return CKM_SHA3_384_RSA_PKCS_PSS;
    case TBID_SHA3_512_RSA_PKCS_PSS:
        return CKM_SHA3_512_RSA_PKCS_PSS;
    case TBID_SHA3_224_RSA_PKCS_PSS:
        return CKM_SHA3_224_RSA_PKCS_PSS;
    case TBID_RSA_PKCS_OAEP:
        return CKM_RSA_PKCS_OAEP;
    case TBID_RSA_X_509:
        return CKM_RSA_X_509;
    case TBID_RSA_X9_31:
        return CKM_RSA_X9_31;
    case TBID_RSA_X9_31_KEY_PAIR_GEN:
        return CKM_RSA_X9_31_KEY_PAIR_GEN;
    case TBID_EC_KEY_PAIR_GEN:
        return CKM_EC_KEY_PAIR_GEN;
    case TBID_ECDSA:
        return CKM_ECDSA;
    case TBID_ECDSA_SHA1:
        return CKM_ECDSA_SHA1;
    case TBID_ECDSA_SHA224:
        return CKM_ECDSA_SHA224;
    case TBID_ECDSA_SHA256:
        return CKM_ECDSA_SHA256;
    case TBID_ECDSA_SHA384:
        return CKM_ECDSA_SHA384;
    case TBID_ECDSA_SHA512:
        return CKM_ECDSA_SHA512;
    case TBID_ECDSA_SHA3_224:
        return CKM_ECDSA_SHA3_224;
    case TBID_ECDSA_SHA3_256:
        return CKM_ECDSA_SHA3_256;
    case TBID_ECDSA_SHA3_384:
        return CKM_ECDSA_SHA3_384;
    case TBID_ECDSA_SHA3_512:
        return CKM_ECDSA_SHA3_512;
    case TBID_ECDH1_DERIVE:
        return CKM_ECDH1_DERIVE;
    case TBID_ECDH1_COFACTOR_DERIVE:
        return CKM_ECDH1_COFACTOR_DERIVE;
    case TBID_EC_EDWARDS_KEY_PAIR_GEN:
        return CKM_EC_EDWARDS_KEY_PAIR_GEN;
    case TBID_EC_MONTGOMERY_KEY_PAIR_GEN:
        return CKM_EC_MONTGOMERY_KEY_PAIR_GEN;
    case TBID_EDDSA:
        return CKM_EDDSA;
    case TBID_HKDF_DERIVE:
        return CKM_HKDF_DERIVE;
    case TBID_SHA_1:
        return CKM_SHA_1;
    case TBID_SHA_1_HMAC:
        return CKM_SHA_1_HMAC;
    case TBID_SHA_1_HMAC_GENERAL:
        return CKM_SHA_1_HMAC_GENERAL;
    case TBID_SHA1_KEY_DERIVATION:
        return CKM_SHA1_KEY_DERIVATION;
    case TBID_SHA_1_KEY_GEN:
        return CKM_SHA_1_KEY_GEN;
    case TBID_SHA224:
        return CKM_SHA224;
    case TBID_SHA224_HMAC:
        return CKM_SHA224_HMAC;
    case TBID_SHA224_HMAC_GENERAL:
        return CKM_SHA224_HMAC_GENERAL;
    case TBID_SHA224_KEY_DERIVATION:
        return CKM_SHA224_KEY_DERIVATION;
    case TBID_SHA224_KEY_GEN:
        return CKM_SHA224_KEY_GEN;
    case TBID_SHA256:
        return CKM_SHA256;
    case TBID_SHA256_HMAC:
        return CKM_SHA256_HMAC;
    case TBID_SHA256_HMAC_GENERAL:
        return CKM_SHA256_HMAC_GENERAL;
    case TBID_SHA256_KEY_DERIVATION:
        return CKM_SHA256_KEY_DERIVATION;
    case TBID_SHA256_KEY_GEN:
        return CKM_SHA256_KEY_GEN;
    case TBID_SHA384:
        return CKM_SHA384;
    case TBID_SHA384_HMAC:
        return CKM_SHA384_HMAC;
    case TBID_SHA384_HMAC_GENERAL:
        return CKM_SHA384_HMAC_GENERAL;
    case TBID_SHA384_KEY_DERIVATION:
        return CKM_SHA384_KEY_DERIVATION;
    case TBID_SHA384_KEY_GEN:
        return CKM_SHA384_KEY_GEN;
    case TBID_SHA512:
        return CKM_SHA512;
    case TBID_SHA512_HMAC:
        return CKM_SHA512_HMAC;
    case TBID_SHA512_HMAC_GENERAL:
        return CKM_SHA512_HMAC_GENERAL;
    case TBID_SHA512_KEY_DERIVATION:
        return CKM_SHA512_KEY_DERIVATION;
    case TBID_SHA512_KEY_GEN:
        return CKM_SHA512_KEY_GEN;
    case TBID_SHA512_224:
        return CKM_SHA512_224;
    case TBID_SHA512_224_HMAC:
        return CKM_SHA512_224_HMAC;
    case TBID_SHA512_224_HMAC_GENERAL:
        return CKM_SHA512_224_HMAC_GENERAL;
    case TBID_SHA512_224_KEY_DERIVATION:
        return CKM_SHA512_224_KEY_DERIVATION;
    case TBID_SHA512_224_KEY_GEN:
        return CKM_SHA512_224_KEY_GEN;
    case TBID_SHA512_256:
        return CKM_SHA512_256;
    case TBID_SHA512_256_HMAC:
        return CKM_SHA512_256_HMAC;
    case TBID_SHA512_256_HMAC_GENERAL:
        return CKM_SHA512_256_HMAC_GENERAL;
    case TBID_SHA512_256_KEY_DERIVATION:
        return CKM_SHA512_256_KEY_DERIVATION;
    case TBID_SHA512_256_KEY_GEN:
        return CKM_SHA512_256_KEY_GEN;
    case TBID_SHA512_T:
        return CKM_SHA512_T;
    case TBID_SHA512_T_HMAC:
        return CKM_SHA512_T_HMAC;
    case TBID_SHA512_T_HMAC_GENERAL:
        return CKM_SHA512_T_HMAC_GENERAL;
    case TBID_SHA512_T_KEY_DERIVATION:
        return CKM_SHA512_T_KEY_DERIVATION;
    case TBID_SHA512_T_KEY_GEN:
        return CKM_SHA512_T_KEY_GEN;
    case TBID_SHA3_224:
        return CKM_SHA3_224;
    case TBID_SHA3_224_HMAC:
        return CKM_SHA3_224_HMAC;
    case TBID_SHA3_224_HMAC_GENERAL:
        return CKM_SHA3_224_HMAC_GENERAL;
    case TBID_SHA3_224_KEY_DERIVATION:
        return CKM_SHA3_224_KEY_DERIVATION;
    case TBID_SHA3_224_KEY_GEN:
        return CKM_SHA3_224_KEY_GEN;
    case TBID_SHA3_256:
        return CKM_SHA3_256;
    case TBID_SHA3_256_HMAC:
        return CKM_SHA3_256_HMAC;
    case TBID_SHA3_256_HMAC_GENERAL:
        return CKM_SHA3_256_HMAC_GENERAL;
    case TBID_SHA3_256_KEY_DERIVATION:
        return CKM_SHA3_256_KEY_DERIVATION;
    case TBID_SHA3_256_KEY_GEN:
        return CKM_SHA3_256_KEY_GEN;
    case TBID_SHA3_384:
        return CKM_SHA3_384;
    case TBID_SHA3_384_HMAC:
        return CKM_SHA3_384_HMAC;
    case TBID_SHA3_384_HMAC_GENERAL:
        return CKM_SHA3_384_HMAC_GENERAL;
    case TBID_SHA3_384_KEY_DERIVATION:
        return CKM_SHA3_384_KEY_DERIVATION;
    case TBID_SHA3_384_KEY_GEN:
        return CKM_SHA3_384_KEY_GEN;
    case TBID_SHA3_512:
        return CKM_SHA3_512;
    case TBID_SHA3_512_HMAC:
        return CKM_SHA3_512_HMAC;
    case TBID_SHA3_512_HMAC_GENERAL:
        return CKM_SHA3_512_HMAC_GENERAL;
    case TBID_SHA3_512_KEY_DERIVATION:
        return CKM_SHA3_512_KEY_DERIVATION;
    case TBID_SHA3_512_KEY_GEN:
        return CKM_SHA3_512_KEY_GEN;
    case TBID_ML_DSA_KEY_PAIR_GEN:
        return CKM_ML_DSA_KEY_PAIR_GEN;
    case TBID_ML_DSA:
        return CKM_ML_DSA;
    case TBID_HASH_ML_DSA:
        return CKM_HASH_ML_DSA;
    case TBID_HASH_ML_DSA_SHA224:
        return CKM_HASH_ML_DSA_SHA224;
    case TBID_HASH_ML_DSA_SHA256:
        return CKM_HASH_ML_DSA_SHA256;
    case TBID_HASH_ML_DSA_SHA384:
        return CKM_HASH_ML_DSA_SHA384;
    case TBID_HASH_ML_DSA_SHA512:
        return CKM_HASH_ML_DSA_SHA512;
    case TBID_HASH_ML_DSA_SHA3_224:
        return CKM_HASH_ML_DSA_SHA3_224;
    case TBID_HASH_ML_DSA_SHA3_256:
        return CKM_HASH_ML_DSA_SHA3_256;
    case TBID_HASH_ML_DSA_SHA3_384:
        return CKM_HASH_ML_DSA_SHA3_384;
    case TBID_HASH_ML_DSA_SHA3_512:
        return CKM_HASH_ML_DSA_SHA3_512;
    case TBID_HASH_ML_DSA_SHAKE128:
        return CKM_HASH_ML_DSA_SHAKE128;
    case TBID_HASH_ML_DSA_SHAKE256:
        return CKM_HASH_ML_DSA_SHAKE256;
    case TBID_ML_KEM_KEY_PAIR_GEN:
        return CKM_ML_KEM_KEY_PAIR_GEN;
    case TBID_ML_KEM:
        return CKM_ML_KEM;
    case TBID_SLH_DSA_KEY_PAIR_GEN:
        return CKM_SLH_DSA_KEY_PAIR_GEN;
    case TBID_SLH_DSA:
        return CKM_SLH_DSA;
    case TBID_HASH_SLH_DSA:
        return CKM_HASH_SLH_DSA;
    case TBID_HASH_SLH_DSA_SHA224:
        return CKM_HASH_SLH_DSA_SHA224;
    case TBID_HASH_SLH_DSA_SHA256:
        return CKM_HASH_SLH_DSA_SHA256;
    case TBID_HASH_SLH_DSA_SHA384:
        return CKM_HASH_SLH_DSA_SHA384;
    case TBID_HASH_SLH_DSA_SHA512:
        return CKM_HASH_SLH_DSA_SHA512;
    case TBID_HASH_SLH_DSA_SHA3_224:
        return CKM_HASH_SLH_DSA_SHA3_224;
    case TBID_HASH_SLH_DSA_SHA3_256:
        return CKM_HASH_SLH_DSA_SHA3_256;
    case TBID_HASH_SLH_DSA_SHA3_384:
        return CKM_HASH_SLH_DSA_SHA3_384;
    case TBID_HASH_SLH_DSA_SHA3_512:
        return CKM_HASH_SLH_DSA_SHA3_512;
    case TBID_HASH_SLH_DSA_SHAKE128:
        return CKM_HASH_SLH_DSA_SHAKE128;
    case TBID_HASH_SLH_DSA_SHAKE256:
        return CKM_HASH_SLH_DSA_SHAKE256;
    case TBID_AES_KEY_GEN:
        return CKM_AES_KEY_GEN;
    case TBID_AES_ECB:
        return CKM_AES_ECB;
    case TBID_AES_CBC:
        return CKM_AES_CBC;
    case TBID_AES_CBC_PAD:
        return CKM_AES_CBC_PAD;
    case TBID_AES_OFB:
        return CKM_AES_OFB;
    case TBID_AES_CFB128:
        return CKM_AES_CFB128;
    case TBID_AES_CFB1:
        return CKM_AES_CFB1;
    case TBID_AES_CFB8:
        return CKM_AES_CFB8;
    case TBID_AES_CTR:
        return CKM_AES_CTR;
    case TBID_AES_CTS:
        return CKM_AES_CTS;
    case TBID_AES_GCM:
        return CKM_AES_GCM;
    case TBID_AES_MAC:
        return CKM_AES_MAC;
    case TBID_AES_MAC_GENERAL:
        return CKM_AES_MAC_GENERAL;
    case TBID_AES_CCM:
        return CKM_AES_CCM;
    case TBID_AES_CMAC:
        return CKM_AES_CMAC;
    case TBID_AES_CMAC_GENERAL:
        return CKM_AES_CMAC_GENERAL;
    case TBID_AES_XCBC_MAC:
        return CKM_AES_XCBC_MAC;
    case TBID_AES_XCBC_MAC_96:
        return CKM_AES_XCBC_MAC_96;
    case TBID_AES_GMAC:
        return CKM_AES_GMAC;
    case TBID_CHACHA20_POLY1305:
        return CKM_CHACHA20_POLY1305;
    case TBID_GENERIC_SECRET_KEY_GEN:
        return CKM_GENERIC_SECRET_KEY_GEN;
    default:
        return CK_UNAVAILABLE_INFORMATION;
    }
}

int p11prov_mech_to_tbid(CK_MECHANISM_TYPE mech)
{
    switch (mech) {
    case CKM_RSA_PKCS_KEY_PAIR_GEN:
        return TBID_RSA_PKCS_KEY_PAIR_GEN;
    case CKM_RSA_PKCS:
        return TBID_RSA_PKCS;
    case CKM_SHA1_RSA_PKCS:
        return TBID_SHA1_RSA_PKCS;
    case CKM_SHA224_RSA_PKCS:
        return TBID_SHA224_RSA_PKCS;
    case CKM_SHA256_RSA_PKCS:
        return TBID_SHA256_RSA_PKCS;
    case CKM_SHA384_RSA_PKCS:
        return TBID_SHA384_RSA_PKCS;
    case CKM_SHA512_RSA_PKCS:
        return TBID_SHA512_RSA_PKCS;
    case CKM_SHA3_224_RSA_PKCS:
        return TBID_SHA3_224_RSA_PKCS;
    case CKM_SHA3_256_RSA_PKCS:
        return TBID_SHA3_256_RSA_PKCS;
    case CKM_SHA3_384_RSA_PKCS:
        return TBID_SHA3_384_RSA_PKCS;
    case CKM_SHA3_512_RSA_PKCS:
        return TBID_SHA3_512_RSA_PKCS;
    case CKM_RSA_PKCS_PSS:
        return TBID_RSA_PKCS_PSS;
    case CKM_SHA1_RSA_PKCS_PSS:
        return TBID_SHA1_RSA_PKCS_PSS;
    case CKM_SHA256_RSA_PKCS_PSS:
        return TBID_SHA256_RSA_PKCS_PSS;
    case CKM_SHA384_RSA_PKCS_PSS:
        return TBID_SHA384_RSA_PKCS_PSS;
    case CKM_SHA512_RSA_PKCS_PSS:
        return TBID_SHA512_RSA_PKCS_PSS;
    case CKM_SHA224_RSA_PKCS_PSS:
        return TBID_SHA224_RSA_PKCS_PSS;
    case CKM_SHA3_256_RSA_PKCS_PSS:
        return TBID_SHA3_256_RSA_PKCS_PSS;
    case CKM_SHA3_384_RSA_PKCS_PSS:
        return TBID_SHA3_384_RSA_PKCS_PSS;
    case CKM_SHA3_512_RSA_PKCS_PSS:
        return TBID_SHA3_512_RSA_PKCS_PSS;
    case CKM_SHA3_224_RSA_PKCS_PSS:
        return TBID_SHA3_224_RSA_PKCS_PSS;
    case CKM_RSA_PKCS_OAEP:
        return TBID_RSA_PKCS_OAEP;
    case CKM_RSA_X_509:
        return TBID_RSA_X_509;
    case CKM_RSA_X9_31:
        return TBID_RSA_X9_31;
    case CKM_RSA_X9_31_KEY_PAIR_GEN:
        return TBID_RSA_X9_31_KEY_PAIR_GEN;
    case CKM_EC_KEY_PAIR_GEN:
        return TBID_EC_KEY_PAIR_GEN;
    case CKM_ECDSA:
        return TBID_ECDSA;
    case CKM_ECDSA_SHA1:
        return TBID_ECDSA_SHA1;
    case CKM_ECDSA_SHA224:
        return TBID_ECDSA_SHA224;
    case CKM_ECDSA_SHA256:
        return TBID_ECDSA_SHA256;
    case CKM_ECDSA_SHA384:
        return TBID_ECDSA_SHA384;
    case CKM_ECDSA_SHA512:
        return TBID_ECDSA_SHA512;
    case CKM_ECDSA_SHA3_224:
        return TBID_ECDSA_SHA3_224;
    case CKM_ECDSA_SHA3_256:
        return TBID_ECDSA_SHA3_256;
    case CKM_ECDSA_SHA3_384:
        return TBID_ECDSA_SHA3_384;
    case CKM_ECDSA_SHA3_512:
        return TBID_ECDSA_SHA3_512;
    case CKM_ECDH1_DERIVE:
        return TBID_ECDH1_DERIVE;
    case CKM_ECDH1_COFACTOR_DERIVE:
        return TBID_ECDH1_COFACTOR_DERIVE;
    case CKM_EC_EDWARDS_KEY_PAIR_GEN:
        return TBID_EC_EDWARDS_KEY_PAIR_GEN;
    case CKM_EC_MONTGOMERY_KEY_PAIR_GEN:
        return TBID_EC_MONTGOMERY_KEY_PAIR_GEN;
    case CKM_EDDSA:
        return TBID_EDDSA;
    case CKM_HKDF_DERIVE:
        return TBID_HKDF_DERIVE;
    case CKM_SHA_1:
        return TBID_SHA_1;
    case CKM_SHA_1_HMAC:
        return TBID_SHA_1_HMAC;
    case CKM_SHA_1_HMAC_GENERAL:
        return TBID_SHA_1_HMAC_GENERAL;
    case CKM_SHA1_KEY_DERIVATION:
        return TBID_SHA1_KEY_DERIVATION;
    case CKM_SHA_1_KEY_GEN:
        return TBID_SHA_1_KEY_GEN;
    case CKM_SHA224:
        return TBID_SHA224;
    case CKM_SHA224_HMAC:
        return TBID_SHA224_HMAC;
    case CKM_SHA224_HMAC_GENERAL:
        return TBID_SHA224_HMAC_GENERAL;
    case CKM_SHA224_KEY_DERIVATION:
        return TBID_SHA224_KEY_DERIVATION;
    case CKM_SHA224_KEY_GEN:
        return TBID_SHA224_KEY_GEN;
    case CKM_SHA256:
        return TBID_SHA256;
    case CKM_SHA256_HMAC:
        return TBID_SHA256_HMAC;
    case CKM_SHA256_HMAC_GENERAL:
        return TBID_SHA256_HMAC_GENERAL;
    case CKM_SHA256_KEY_DERIVATION:
        return TBID_SHA256_KEY_DERIVATION;
    case CKM_SHA256_KEY_GEN:
        return TBID_SHA256_KEY_GEN;
    case CKM_SHA384:
        return TBID_SHA384;
    case CKM_SHA384_HMAC:
        return TBID_SHA384_HMAC;
    case CKM_SHA384_HMAC_GENERAL:
        return TBID_SHA384_HMAC_GENERAL;
    case CKM_SHA384_KEY_DERIVATION:
        return TBID_SHA384_KEY_DERIVATION;
    case CKM_SHA384_KEY_GEN:
        return TBID_SHA384_KEY_GEN;
    case CKM_SHA512:
        return TBID_SHA512;
    case CKM_SHA512_HMAC:
        return TBID_SHA512_HMAC;
    case CKM_SHA512_HMAC_GENERAL:
        return TBID_SHA512_HMAC_GENERAL;
    case CKM_SHA512_KEY_DERIVATION:
        return TBID_SHA512_KEY_DERIVATION;
    case CKM_SHA512_KEY_GEN:
        return TBID_SHA512_KEY_GEN;
    case CKM_SHA512_224:
        return TBID_SHA512_224;
    case CKM_SHA512_224_HMAC:
        return TBID_SHA512_224_HMAC;
    case CKM_SHA512_224_HMAC_GENERAL:
        return TBID_SHA512_224_HMAC_GENERAL;
    case CKM_SHA512_224_KEY_DERIVATION:
        return TBID_SHA512_224_KEY_DERIVATION;
    case CKM_SHA512_224_KEY_GEN:
        return TBID_SHA512_224_KEY_GEN;
    case CKM_SHA512_256:
        return TBID_SHA512_256;
    case CKM_SHA512_256_HMAC:
        return TBID_SHA512_256_HMAC;
    case CKM_SHA512_256_HMAC_GENERAL:
        return TBID_SHA512_256_HMAC_GENERAL;
    case CKM_SHA512_256_KEY_DERIVATION:
        return TBID_SHA512_256_KEY_DERIVATION;
    case CKM_SHA512_256_KEY_GEN:
        return TBID_SHA512_256_KEY_GEN;
    case CKM_SHA512_T:
        return TBID_SHA512_T;
    case CKM_SHA512_T_HMAC:
        return TBID_SHA512_T_HMAC;
    case CKM_SHA512_T_HMAC_GENERAL:
        return TBID_SHA512_T_HMAC_GENERAL;
    case CKM_SHA512_T_KEY_DERIVATION:
        return TBID_SHA512_T_KEY_DERIVATION;
    case CKM_SHA512_T_KEY_GEN:
        return TBID_SHA512_T_KEY_GEN;
    case CKM_SHA3_224:
        return TBID_SHA3_224;
    case CKM_SHA3_224_HMAC:
        return TBID_SHA3_224_HMAC;
    case CKM_SHA3_224_HMAC_GENERAL:
        return TBID_SHA3_224_HMAC_GENERAL;
    case CKM_SHA3_224_KEY_DERIVATION:
        return TBID_SHA3_224_KEY_DERIVATION;
    case CKM_SHA3_224_KEY_GEN:
        return TBID_SHA3_224_KEY_GEN;
    case CKM_SHA3_256:
        return TBID_SHA3_256;
    case CKM_SHA3_256_HMAC:
        return TBID_SHA3_256_HMAC;
    case CKM_SHA3_256_HMAC_GENERAL:
        return TBID_SHA3_256_HMAC_GENERAL;
    case CKM_SHA3_256_KEY_DERIVATION:
        return TBID_SHA3_256_KEY_DERIVATION;
    case CKM_SHA3_256_KEY_GEN:
        return TBID_SHA3_256_KEY_GEN;
    case CKM_SHA3_384:
        return TBID_SHA3_384;
    case CKM_SHA3_384_HMAC:
        return TBID_SHA3_384_HMAC;
    case CKM_SHA3_384_HMAC_GENERAL:
        return TBID_SHA3_384_HMAC_GENERAL;
    case CKM_SHA3_384_KEY_DERIVATION:
        return TBID_SHA3_384_KEY_DERIVATION;
    case CKM_SHA3_384_KEY_GEN:
        return TBID_SHA3_384_KEY_GEN;
    case CKM_SHA3_512:
        return TBID_SHA3_512;
    case CKM_SHA3_512_HMAC:
        return TBID_SHA3_512_HMAC;
    case CKM_SHA3_512_HMAC_GENERAL:
        return TBID_SHA3_512_HMAC_GENERAL;
    case CKM_SHA3_512_KEY_DERIVATION:
        return TBID_SHA3_512_KEY_DERIVATION;
    case CKM_SHA3_512_KEY_GEN:
        return TBID_SHA3_512_KEY_GEN;
    case CKM_ML_DSA_KEY_PAIR_GEN:
        return TBID_ML_DSA_KEY_PAIR_GEN;
    case CKM_ML_DSA:
        return TBID_ML_DSA;
    case CKM_HASH_ML_DSA:
        return TBID_HASH_ML_DSA;
    case CKM_HASH_ML_DSA_SHA224:
        return TBID_HASH_ML_DSA_SHA224;
    case CKM_HASH_ML_DSA_SHA256:
        return TBID_HASH_ML_DSA_SHA256;
    case CKM_HASH_ML_DSA_SHA384:
        return TBID_HASH_ML_DSA_SHA384;
    case CKM_HASH_ML_DSA_SHA512:
        return TBID_HASH_ML_DSA_SHA512;
    case CKM_HASH_ML_DSA_SHA3_224:
        return TBID_HASH_ML_DSA_SHA3_224;
    case CKM_HASH_ML_DSA_SHA3_256:
        return TBID_HASH_ML_DSA_SHA3_256;
    case CKM_HASH_ML_DSA_SHA3_384:
        return TBID_HASH_ML_DSA_SHA3_384;
    case CKM_HASH_ML_DSA_SHA3_512:
        return TBID_HASH_ML_DSA_SHA3_512;
    case CKM_HASH_ML_DSA_SHAKE128:
        return TBID_HASH_ML_DSA_SHAKE128;
    case CKM_HASH_ML_DSA_SHAKE256:
        return TBID_HASH_ML_DSA_SHAKE256;
    case CKM_ML_KEM_KEY_PAIR_GEN:
        return TBID_ML_KEM_KEY_PAIR_GEN;
    case CKM_ML_KEM:
        return TBID_ML_KEM;
    case CKM_SLH_DSA_KEY_PAIR_GEN:
        return TBID_SLH_DSA_KEY_PAIR_GEN;
    case CKM_SLH_DSA:
        return TBID_SLH_DSA;
    case CKM_HASH_SLH_DSA:
        return TBID_HASH_SLH_DSA;
    case CKM_HASH_SLH_DSA_SHA224:
        return TBID_HASH_SLH_DSA_SHA224;
    case CKM_HASH_SLH_DSA_SHA256:
        return TBID_HASH_SLH_DSA_SHA256;
    case CKM_HASH_SLH_DSA_SHA384:
        return TBID_HASH_SLH_DSA_SHA384;
    case CKM_HASH_SLH_DSA_SHA512:
        return TBID_HASH_SLH_DSA_SHA512;
    case CKM_HASH_SLH_DSA_SHA3_224:
        return TBID_HASH_SLH_DSA_SHA3_224;
    case CKM_HASH_SLH_DSA_SHA3_256:
        return TBID_HASH_SLH_DSA_SHA3_256;
    case CKM_HASH_SLH_DSA_SHA3_384:
        return TBID_HASH_SLH_DSA_SHA3_384;
    case CKM_HASH_SLH_DSA_SHA3_512:
        return TBID_HASH_SLH_DSA_SHA3_512;
    case CKM_HASH_SLH_DSA_SHAKE128:
        return TBID_HASH_SLH_DSA_SHAKE128;
    case CKM_HASH_SLH_DSA_SHAKE256:
        return TBID_HASH_SLH_DSA_SHAKE256;
    case CKM_AES_KEY_GEN:
        return TBID_AES_KEY_GEN;
    case CKM_AES_ECB:
        return TBID_AES_ECB;
    case CKM_AES_CBC:
        return TBID_AES_CBC;
    case CKM_AES_CBC_PAD:
        return TBID_AES_CBC_PAD;
    case CKM_AES_OFB:
        return TBID_AES_OFB;
    case CKM_AES_CFB128:
        return TBID_AES_CFB128;
    case CKM_AES_CFB1:
        return TBID_AES_CFB1;
    case CKM_AES_CFB8:
        return TBID_AES_CFB8;
    case CKM_AES_CTR:
        return TBID_AES_CTR;
    case CKM_AES_CTS:
        return TBID_AES_CTS;
    case CKM_AES_GCM:
        return TBID_AES_GCM;
    case CKM_AES_MAC:
        return TBID_AES_MAC;
    case CKM_AES_MAC_GENERAL:
        return TBID_AES_MAC_GENERAL;
    case CKM_AES_CCM:
        return TBID_AES_CCM;
    case CKM_AES_CMAC:
        return TBID_AES_CMAC;
    case CKM_AES_CMAC_GENERAL:
        return TBID_AES_CMAC_GENERAL;
    case CKM_AES_XCBC_MAC:
        return TBID_AES_XCBC_MAC;
    case CKM_AES_XCBC_MAC_96:
        return TBID_AES_XCBC_MAC_96;
    case CKM_AES_GMAC:
        return TBID_AES_GMAC;
    case CKM_CHACHA20_POLY1305:
        return TBID_CHACHA20_POLY1305;
    case CKM_GENERIC_SECRET_KEY_GEN:
        return TBID_GENERIC_SECRET_KEY_GEN;
    default:
        return -1;
    }
}

CK_RV p11prov_get_mech_state_table(P11PROV_CTX *ctx, bool available[TBID_SIZE])
{
    P11PROV_SLOTS_CTX *slots;
    P11PROV_SLOT *slot;
    int slot_idx = 0;
    CK_RV ret;

    ret = p11prov_take_slots(ctx, &slots);
    if (ret != CKR_OK) {
        return ret;
    }

    for (slot = p11prov_fetch_slot(slots, &slot_idx); slot != NULL;
         slot = p11prov_fetch_slot(slots, &slot_idx)) {

        CK_MECHANISM_TYPE *mechs;
        int nmechs;
        nmechs = p11prov_slot_get_mechanisms(slot, &mechs);

        for (int i = 0; i < nmechs; i++) {
            int tbid = p11prov_mech_to_tbid(mechs[i]);
            if (tbid == -1) {
                continue;
            }
            available[tbid] = true;
        }
    }
    p11prov_return_slots(slots);

    return CKR_OK;
}

void p11prov_assign_alg(OSSL_ALGORITHM *dest, const OSSL_ALGORITHM *algs,
                        int idx, const char *fips_property)
{
    *dest = algs[idx];
    if (fips_property) {
        dest->property_definition = fips_property;
    }
}
